# Generated by Django 5.1.6 on 2025-02-27 06:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_examresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_taken', models.IntegerField(help_text='Total time spent on the exam in seconds')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Time when the user started the exam')),
                ('end_time', models.DateTimeField(blank=True, help_text='Time when the user submitted the exam', null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
